---
clusterName: talos-cluster
talosVersion: v1.8.1
kubernetesVersion: v1.30.1
endpoint: https://192.168.64.101:6443
allowSchedulingOnMasters: true
# Patch globaux
patches:
  - |-
    - op: replace
      path: /machine/network/kubespan
      value:
        enabled: true 
# Patch aux controlPlanes uniquement
nodes:
  - hostname: cp-1
    ipAddress: 192.168.64.101
    controlPlane: true
    installDisk: /dev/sda
  - hostname: cp-2
    ipAddress: 192.168.64.102
    controlPlane: true
    installDisk: /dev/sda
  - hostname: cp-3
    ipAddress: 192.168.64.103
    controlPlane: true
    installDisk: /dev/sda
  - hostname: worker-1
    ipAddress: 192.168.64.104
    controlPlane: false
    installDisk: /dev/sda
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
