---
clusterName: talos-cluster
talosVersion: v1.8.1
kubernetesVersion: v1.30.1
endpoint: https://192.168.1.101:6443
allowSchedulingOnMasters: true
# Patch globaux
patches:
  - |-
    - op: replace
      path: /machine/network/kubespan
      value:
        enabled: true 
# Patch aux controlPlanes uniquement
controlPlane:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: "true"
nodes:
  - hostname: cp-1
    ipAddress: 192.168.1.101
    controlPlane: true
    installDisk: /dev/sda
  - hostname: cp-2
    ipAddress: 192.168.1.102
    controlPlane: true
    installDisk: /dev/sda
  - hostname: cp-3
    ipAddress: 192.168.1.103
    controlPlane: true
    installDisk: /dev/sda
  - hostname: worker-1
    ipAddress: 192.168.1.114
    controlPlane: false
    installDisk: /dev/sda
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
