---
clusterName: talos-ext
talosVersion: v1.8.1
kubernetesVersion: v1.30.1
endpoint: https://192.168.1.7:6443
allowSchedulingOnMasters: true
nodes:
  - hostname: cp-1
    ipAddress: 192.168.1.7
    controlPlane: true
    installDisk: /dev/sda
